services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: brigadas_medicas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: arbolito
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: