deploy:
  runs-on: ubuntu-latest
  needs: build-and-push

  steps:
  - name: Deploy to AWS EC2
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.AWS_EC2_HOST }}
      username: ${{ secrets.AWS_EC2_USER }}
      key: ${{ secrets.AWS_EC2_KEY }}
      port: 22
      script: |
        # Detener y eliminar cualquier contenedor anterior con el mismo nombre
        docker stop brigadas_service || true
        docker rm brigadas_service || true

        # Descargar la última imagen de Docker Hub
        docker pull ${{ secrets.DOCKER_USERNAME }}/brigadas:latest

        # Ejecutar el contenedor con los puertos adecuados
        docker run -d -p 8000:8000 --name brigadas_service ${{ secrets.DOCKER_USERNAME }}/brigadas:latest
