deploy:
  runs-on: ubuntu-latest
  needs: build-and-push

  steps:
  - name: Deploy to AWS EC2
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.AWS_EC2_HOST }}
      username: ${{ secrets.AWS_EC2_USER }}
      key: ${{ secrets.AWS_EC2_KEY }}
      port: 22
      script: |
        # Crear la carpeta si no existe
        mkdir -p /home/ec2-user/BrigadAS
        cd /home/ec2-user/BrigadAS

        # Crear el archivo docker-compose.yml si no existe
        cat <<EOF > docker-compose.yml
        version: '3'
        services:
          db:
            image: postgres:13
            environment:
              POSTGRES_DB: brigadas_medicas
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: arbolito
            volumes:
              - postgres_data:/var/lib/postgresql/data

          web:
            image: ${{ secrets.DOCKER_USERNAME }}/brigadas:latest
            ports:
              - "8000:8000"
            depends_on:
              - db

        volumes:
          postgres_data:
        EOF

        # Descargar la última versión de la imagen desde Docker Hub
        docker pull ${{ secrets.DOCKER_USERNAME }}/brigadas:latest

        # Detener y eliminar contenedores previos si existen
        docker-compose down || true

        # Levantar los servicios
        docker-compose up -d
