# Generated by Django 5.1 on 2025-02-05 10:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='registro_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='registro_user_permissions_set', to='auth.permission')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.especialidad')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('apellidos_nombres', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('sector', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('afiliado_seguro', models.BooleanField(default=False)),
                ('discapacidad', models.BooleanField(default=False)),
                ('porcentaje_discapacidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tipo_discapacidad', models.CharField(blank=True, max_length=100, null=True)),
                ('antecedentes_patologicos_personales', models.TextField()),
                ('antecedentes_patologicos_familiares', models.TextField()),
                ('presion_arterial', models.CharField(blank=True, max_length=20, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diagnostico_imc', models.CharField(max_length=100)),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('frecuencia_respiratoria', models.IntegerField()),
                ('nivel_glucosa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saturacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diagnostico', models.TextField()),
                ('cie_10', models.CharField(default='No especificado', max_length=20)),
                ('observacion', models.TextField()),
                ('responsable', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.especialidad')),
            ],
        ),
    ]
