# Generated by Django 5.1 on 2024-08-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_paciente_sexo_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='presion_arterial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
